### ISSUE TITLE
Strange output and error with particuliar output

### ISSUE THREAD

**Issue by natir** [YannGarbe/PFE_2018#1]
When I run this command : 
```
python3 Analyzer.py gentle paf ../minimap2.paf ../minimap.paf
```

This error was raise:
```
Traceback (most recent call last):
  File "Analyzer.py", line 75, in <module>
    main(sys.argv)
  File "Analyzer.py", line 27, in main
    for i_interval in tools.sort_Intervals_start(dict_data['1']['6696']['+'], True):
KeyError: '6696'
```

minimap.paf:
```
1	1860	44	1762	-	56208	7490	2642	4313	516	1718	255	cm:i:80
```
minimap2.paf:
```
1	1860	44	1762	-	56208	7490	2642	4313	549	1753	0	tp:A:S	cm:i:86	s1:i:531	dv:f:0.1356
```

**Comment by YannGarbe** [comment]
The error has been fixed. About the duplication, it's because there two intervals :
[1] [56208] and [56208] [1]. I'll fix it asap

**Comment by YannGarbe** [comment]
The duplication problem has been fixed
